[phases.setup]
nixPkgs = ["python311", "ffmpeg"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.build]
cmds = ["mkdir -p static/audio"]

[start]
cmd = "gunicorn app:app --bind 0.0.0.0:$PORT"
